<a href="https://colab.research.google.com/github/Sairabanu32/project1/blob/main/ttn_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hi")
+from google.colab import drive
drive.mount('')

hi

In [7]:
import numpy as np
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
df=pd.read_csv("/content/drive/MyDrive/TTD Intern/Business-price-indexes-december-2025-quarter-csv.csv")

/tmp/ipykernel_11766/2677694432.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/TTD Intern/Business-price-indexes-december-2025-quarter-csv.csv")

In [10]:
df

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,CEPQ.S611,1989.12,456.670842,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
1,CEPQ.S611,1990.03,458.954197,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
2,CEPQ.S611,1990.06,466.717601,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
3,CEPQ.S611,1990.09,462.607563,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
4,CEPQ.S611,1990.12,467.174272,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
81541,PPIQ.SQURS2110,2024.12,1742.000000,FINAL,Index,Producers Price Index - PPI,"Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...",Repair and Maintenance,NaN,NaN,NaN,NaN
81542,PPIQ.SQURS2110,2025.03,1813.000000,FINAL,Index,Producers Price Index - PPI,"Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...",Repair and Maintenance,NaN,NaN,NaN,NaN
81543,PPIQ.SQURS2110,2025.06,1815.000000,FINAL,Index,Producers Price Index - PPI,"Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...",Repair and Maintenance,NaN,NaN,NaN,NaN
81544,PPIQ.SQURS2110,2025.09,1848.000000,FINAL,Index,Producers Price Index - PPI,"Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...",Repair and Maintenance,NaN,NaN,NaN,NaN
81545,PPIQ.SQURS2110,2025.12,1921.000000,FINAL,Index,Producers Price Index - PPI,"Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...",Repair and Maintenance,NaN,NaN,NaN,NaN

In [11]:
df.head(10)

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,CEPQ.S611,1989.12,456.670842,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
1,CEPQ.S611,1990.03,458.954197,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
2,CEPQ.S611,1990.06,466.717601,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
3,CEPQ.S611,1990.09,462.607563,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
4,CEPQ.S611,1990.12,467.174272,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
5,CEPQ.S611,1991.03,471.284309,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
6,CEPQ.S611,1991.06,474.024334,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
7,CEPQ.S611,1991.09,474.937676,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
8,CEPQ.S611,1991.12,478.134372,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN
9,CEPQ.S611,1992.03,483.157751,FINAL,Index,Capital Goods Price Index - CEP,Price Index all groups of capital goods (Base:...,All Groups,NaN,NaN,NaN,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81546 entries, 0 to 81545
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  81546 non-null  object
 1   Period            81546 non-null  float64
 2   Data_value        81146 non-null  float64
 3   STATUS            81546 non-null  object
 4   UNITS             81546 non-null  object
 5   Subject           81546 non-null  object
 6   Group             81546 non-null  object
 7   Series_title_1    81546 non-null  object
 8   Series_title_2    1047 non-null   object
 9   Series_title_3    0 non-null      float64
 10  Series_title_4    0 non-null      float64
 11  Series_title_5    0 non-null      float64
dtypes: float64(5), object(7)
memory usage: 7.5+ MB

In [13]:
df.describe()

,Period,Data_value,Series_title_3,Series_title_4,Series_title_5
count,81546.000000,81146.000000,0.0,0.0,0.0
mean,2010.061530,978.645811,NaN,NaN,NaN
std,10.565156,347.992681,NaN,NaN,NaN
min,1977.120000,-5.800000,NaN,NaN,NaN
25%,2002.060000,765.562679,NaN,NaN,NaN
50%,2012.060000,1000.000000,NaN,NaN,NaN
75%,2019.030000,1141.000000,NaN,NaN,NaN
max,2025.120000,5239.000000,NaN,NaN,NaN

In [14]:
df.shape

(81546, 12)

In [15]:
df.columns

Index(['Series_reference', 'Period', 'Data_value', 'STATUS', 'UNITS',
       'Subject', 'Group', 'Series_title_1', 'Series_title_2',
       'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='object')

In [16]:
df.dtypes

Series_reference     object
Period              float64
Data_value          float64
STATUS               object
UNITS                object
Subject              object
Group                object
Series_title_1       object
Series_title_2       object
Series_title_3      float64
Series_title_4      float64
Series_title_5      float64
dtype: object

In [17]:
df.value_counts()

Series([], Name: count, dtype: int64)

In [27]:
df.isnull().sum()

Series_reference        0
Period                  0
Data_value            400
STATUS                  0
UNITS                   0
Subject                 0
Group                   0
Series_title_1          0
Series_title_2      80499
Series_title_3      81546
Series_title_4      81546
Series_title_5      81546
dtype: int64

In [28]:
print(df.groupby)

<bound method DataFrame.groupby of       Series_reference   Period   Data_value STATUS  UNITS  \
0            CEPQ.S611  1989.12   456.670842  FINAL  Index
1            CEPQ.S611  1990.03   458.954197  FINAL  Index
2            CEPQ.S611  1990.06   466.717601  FINAL  Index
3            CEPQ.S611  1990.09   462.607563  FINAL  Index
4            CEPQ.S611  1990.12   467.174272  FINAL  Index
...                ...      ...          ...    ...    ...
81541   PPIQ.SQURS2110  2024.12  1742.000000  FINAL  Index
81542   PPIQ.SQURS2110  2025.03  1813.000000  FINAL  Index
81543   PPIQ.SQURS2110  2025.06  1815.000000  FINAL  Index
81544   PPIQ.SQURS2110  2025.09  1848.000000  FINAL  Index
81545   PPIQ.SQURS2110  2025.12  1921.000000  FINAL  Index

                               Subject  \
0      Capital Goods Price Index - CEP
1      Capital Goods Price Index - CEP
2      Capital Goods Price Index - CEP
3      Capital Goods Price Index - CEP
4      Capital Goods Price Index - CEP
...                                ...
81541      Producers Price Index - PPI
81542      Producers Price Index - PPI
81543      Producers Price Index - PPI
81544      Producers Price Index - PPI
81545      Producers Price Index - PPI

                                                   Group  \
0      Price Index all groups of capital goods (Base:...
1      Price Index all groups of capital goods (Base:...
2      Price Index all groups of capital goods (Base:...
3      Price Index all groups of capital goods (Base:...
4      Price Index all groups of capital goods (Base:...
...                                                  ...
81541  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81542  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81543  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81544  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81545  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...

               Series_title_1 Series_title_2  Series_title_3  Series_title_4  \
0                  All Groups            NaN             NaN             NaN
1                  All Groups            NaN             NaN             NaN
2                  All Groups            NaN             NaN             NaN
3                  All Groups            NaN             NaN             NaN
4                  All Groups            NaN             NaN             NaN
...                       ...            ...             ...             ...
81541  Repair and Maintenance            NaN             NaN             NaN
81542  Repair and Maintenance            NaN             NaN             NaN
81543  Repair and Maintenance            NaN             NaN             NaN
81544  Repair and Maintenance            NaN             NaN             NaN
81545  Repair and Maintenance            NaN             NaN             NaN

       Series_title_5
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
81541             NaN
81542             NaN
81543             NaN
81544             NaN
81545             NaN

[81546 rows x 12 columns]>

In [29]:
print(df.sort_values)

<bound method DataFrame.sort_values of       Series_reference   Period   Data_value STATUS  UNITS  \
0            CEPQ.S611  1989.12   456.670842  FINAL  Index
1            CEPQ.S611  1990.03   458.954197  FINAL  Index
2            CEPQ.S611  1990.06   466.717601  FINAL  Index
3            CEPQ.S611  1990.09   462.607563  FINAL  Index
4            CEPQ.S611  1990.12   467.174272  FINAL  Index
...                ...      ...          ...    ...    ...
81541   PPIQ.SQURS2110  2024.12  1742.000000  FINAL  Index
81542   PPIQ.SQURS2110  2025.03  1813.000000  FINAL  Index
81543   PPIQ.SQURS2110  2025.06  1815.000000  FINAL  Index
81544   PPIQ.SQURS2110  2025.09  1848.000000  FINAL  Index
81545   PPIQ.SQURS2110  2025.12  1921.000000  FINAL  Index

                               Subject  \
0      Capital Goods Price Index - CEP
1      Capital Goods Price Index - CEP
2      Capital Goods Price Index - CEP
3      Capital Goods Price Index - CEP
4      Capital Goods Price Index - CEP
...                                ...
81541      Producers Price Index - PPI
81542      Producers Price Index - PPI
81543      Producers Price Index - PPI
81544      Producers Price Index - PPI
81545      Producers Price Index - PPI

                                                   Group  \
0      Price Index all groups of capital goods (Base:...
1      Price Index all groups of capital goods (Base:...
2      Price Index all groups of capital goods (Base:...
3      Price Index all groups of capital goods (Base:...
4      Price Index all groups of capital goods (Base:...
...                                                  ...
81541  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81542  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81543  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81544  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...
81545  Outputs (ANZSIC06) - NZSIOC level 4, Base: Dec...

               Series_title_1 Series_title_2  Series_title_3  Series_title_4  \
0                  All Groups            NaN             NaN             NaN
1                  All Groups            NaN             NaN             NaN
2                  All Groups            NaN             NaN             NaN
3                  All Groups            NaN             NaN             NaN
4                  All Groups            NaN             NaN             NaN
...                       ...            ...             ...             ...
81541  Repair and Maintenance            NaN             NaN             NaN
81542  Repair and Maintenance            NaN             NaN             NaN
81543  Repair and Maintenance            NaN             NaN             NaN
81544  Repair and Maintenance            NaN             NaN             NaN
81545  Repair and Maintenance            NaN             NaN             NaN

       Series_title_5
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
81541             NaN
81542             NaN
81543             NaN
81544             NaN
81545             NaN

[81546 rows x 12 columns]>

In [30]:
print(dir(df))

['Data_value', 'Group', 'Period', 'STATUS', 'Series_reference', 'Series_title_1', 'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5', 'Subject', 'T', 'UNITS', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [31]:
df = df.drop('Group', axis=1)
display(df.head())

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,CEPQ.S611,1989.12,456.670842,FINAL,Index,Capital Goods Price Index - CEP,All Groups,NaN,NaN,NaN,NaN
1,CEPQ.S611,1990.03,458.954197,FINAL,Index,Capital Goods Price Index - CEP,All Groups,NaN,NaN,NaN,NaN
2,CEPQ.S611,1990.06,466.717601,FINAL,Index,Capital Goods Price Index - CEP,All Groups,NaN,NaN,NaN,NaN
3,CEPQ.S611,1990.09,462.607563,FINAL,Index,Capital Goods Price Index - CEP,All Groups,NaN,NaN,NaN,NaN
4,CEPQ.S611,1990.12,467.174272,FINAL,Index,Capital Goods Price Index - CEP,All Groups,NaN,NaN,NaN,NaN

In [32]:
print(df.isnull().sum())

Series_reference        0
Period                  0
Data_value            400
STATUS                  0
UNITS                   0
Subject                 0
Series_title_1          0
Series_title_2      80499
Series_title_3      81546
Series_title_4      81546
Series_title_5      81546
dtype: int64

In [33]:
df=df.dropna()
print(df.isnull().sum())

Series_reference    0
Period              0
Data_value          0
STATUS              0
UNITS               0
Subject             0
Series_title_1      0
Series_title_2      0
Series_title_3      0
Series_title_4      0
Series_title_5      0
dtype: int64